name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: pull on palgania server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: pull
          host: ${{ secrets.HOST }}
          username: minecraft
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
